/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AscoltoRouteImport } from './routes/ascolto'
import { Route as DiarioRouteImport } from './routes/diario'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AscoltoRoute = AscoltoRouteImport.update({
  id: '/ascolto',
  path: '/ascolto',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascolto': typeof AscoltoRoute
  '/diario': typeof DiarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascolto': typeof AscoltoRoute
  '/diario': typeof DiarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ascolto': typeof AscoltoRoute
  '/diario': typeof DiarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ascolto' | '/diario'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ascolto' | '/diario'
  id: '__root__' | '/' | '/ascolto' | '/diario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AscoltoRoute: typeof AscoltoRoute
  DiarioRoute: typeof DiarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascolto': {
      id: '/ascolto'
      path: '/ascolto'
      fullPath: '/ascolto'
      preLoaderRoute: typeof AscoltoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AscoltoRoute: AscoltoRoute,
  DiarioRoute: DiarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
